# Monokai-Tasty colors
set $yellow   #ffff87
set $purple   #af87ff
set $green    #a4e400
set $blue     #62d8f1
set $magenta  #fc1a70
set $orange   #ff9700

set $yellow-dim  #b2b25e
set $purple-dim  #7a5eb2
set $green-dim   #729f00
set $blue-dim    #4497a8
set $magenta-dim #b0124e
set $orange-dim  #b26900

set $bg       #1e1e1e
set $bg-dim   #2b2b2b
set $fg       #ffffff
set $fg-dim   #f2f2f2
set $gray     #8a8a8a
set $gray-dim #4b4b4b

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 9

# class                 border     background text  indicator   child_border
client.focused          $green-dim $green-dim $bg   $orange-dim $green-dim
client.focused_inactive $gray-dim  $gray-dim  $fg   $yellow-dim $gray-dim
client.unfocused        $bg        $bg        $gray $gray       $bg
client.urgent           $magenta   $magenta   $fg   $purple     $magenta
client.placeholder      $bg-dim    $bg-dim    $gray $gray       $bg-dim

bar {
    status_command i3status-rs

    position top

    font pango:monospace 11

    colors {
        background $bg
        statusline $fg
        separator  $gray

        focused_workspace  $green-dim  $green-dim $bg
        active_workspace   $yellow-dim $gray-dim  $yellow-dim
        inactive_workspace $bg         $bg        $gray-dim
        urgent_workspace   $magenta    $magenta   $bg
        binding_mode       $purple     $purple    $bg
    }
}
