return {
    -- {
    --     "lervag/vimtex",
    --     -- lazy = false,     -- we don't want to lazy load VimTeX
    --     -- tag = "v2.15", -- uncomment to pin to a specific release
    --     event = { "BufReadPre *.tex", "BufNewFile *.tex" },
    --     init = function()
    --         -- VimTeX configuration goes here, e.g.
    --         vim.g.vimtex_view_method = "zathura"
    --         vim.g.vimtex_compiler_method = "latexrun"
    --     end,
    -- },
    -- {
    --     "micangl/cmp-vimtex",
    --     event = { "BufReadPre *.tex", "BufNewFile *.tex" },
    --     dependencies = {
    --         "hrsh7th/nvim-cmp",
    --     },
    --     config = function()
    --         local cmp = require('cmp')
    --
    --         local opts = cmp.get_config()
    --
    --         table.insert(opts.sources, {
    --             name = 'vimtex'
    --         })
    --
    --         cmp.setup.filetype("tex", opts)
    --     end,
    -- }
}
